version: '3'
services:
  togdemo:
    build:
      dockerfile: ./Dockerfile
      context: ./
    volumes:
      - /home/ec2-user/model_weights:/app/model_weights
    ports:
      - 8000:8000
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1.22
    depends_on:
      - togdemo
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    environment:
      WEBSOCKET: 'true'
      DOMAINS: 'togdemo.info -> togdemo:8000'
      STAGE: 'production' # Don't use production until 'staging' works, default is staging
